spring.application.name=football-feature-engineering-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/football_ai
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

feature-engineering.cron=*/30 * * * * *
feature-engineering.lookback-matches=5
feature-engineering.batch-size=500
feature-engineering.feature-version=v8